# Generated by Django 5.2.17 on 2026-09-09 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=64, unique=True)),
                ('last_modified_watermark', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('running', models.BooleanField(default=False)),
                ('last_ok', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True)),
                ('tasks_upserted', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_id', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('url', models.URLField(max_length=512)),
                ('project_code', models.CharField(db_index=True, max_length=64)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=512)),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, max_length=128)),
                ('status_code', models.CharField(blank=True, max_length=64)),
                ('status_type', models.CharField(blank=True, db_index=True, max_length=32)),
                ('request_type', models.CharField(blank=True, db_index=True, max_length=255)),
                ('epic', models.CharField(blank=True, max_length=255)),
                ('tags', models.TextField(blank=True)),
                ('assets', models.TextField(blank=True)),
                ('components', models.TextField(blank=True)),
                ('workflow_name', models.CharField(blank=True, max_length=255)),
                ('workflow_code', models.CharField(blank=True, max_length=64)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('author_login', models.CharField(blank=True, max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('responsible_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('responsible_login', models.CharField(blank=True, max_length=255)),
                ('modified_by_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('modified_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_alarm', models.DateTimeField(blank=True, null=True)),
                ('parent_task_id', models.CharField(blank=True, max_length=128)),
                ('created_via', models.CharField(blank=True, db_index=True, max_length=32)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_id', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('log_level', models.IntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
                ('operation', models.CharField(blank=True, db_index=True, max_length=64)),
                ('parsed_status', models.CharField(blank=True, max_length=255)),
                ('waiting_for_person', models.CharField(blank=True, max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='er_tasks.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_id', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('owner_login', models.CharField(blank=True, max_length=255)),
                ('minutes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('history_type', models.CharField(blank=True, max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='er_tasks.task')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
